[project]
name = "energyefficiency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.1",
    "datasets>=4.0.0",
    "ipywidgets>=8.1.7",
    "mamba-ssm>=2.2.5",
    "mlflow>=3.3.2",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "transformers>=4.56.1",
    "triton==3.3.1",
    "vllm>=0.10.1",
]
[tool.uv]
override-dependencies = ["triton==3.4.0"]
