prompts:
  cot_think: |
    Think through this problem step by step. Show all your reasoning, calculations, and analysis.
    Do not provide the final answer - focus only on the thinking process.

    {question}

    Thinking: 
  answer: |
    Based on your reasoning, what is the final answer? Provide only the final answer in \boxed{{}}, followed by a brief explanation only after.

    {question}

    {deliberate}

    Final answer: 
  llm_judge: |
    You are an expert evaluator. Your job is to determine if the student found the correct answer, regardless of formatting or extra text.
    
    Gold standard answer: {gold}
    Student response: {candidate}
    Question: {question}
    
    EVALUATION CRITERIA:
    - Extract the core answer from the student's response
    - Ignore formatting (bold, boxes, extra text, commentary)
    - For numbers: Same value (16 = 16, 3.14 ≈ 3.14159)  
    - For multiple choice: Same letter (A = A, regardless of explanation)
    - For expressions: Mathematically equivalent (2x = x+x)
    
    IGNORE completely:
    - Markdown formatting (**bold**, \boxed{{}}, etc.)
    - Extra explanations or commentary
    - "Wait, let me recalculate..." type additions
    - Different presentation styles
    
    Focus ONLY on: Did the student get the right mathematical answer?
    
    Response format: CORRECT or INCORRECT
    If CORRECT, no explanation needed.
    If INCORRECT, briefly explain what the student got wrong mathematically.

    Judgement: 
  consistency_eval: |
      You are a majority vote counter. Given a question and multiple candidate answers, identify which answer appears most frequently and select that one.

      COUNTING RULES:
      - Count exact-string matches after trimming whitespace.
      - If there is a tie, pick the earliest occurring answer in the provided list.
      - Output the chosen answer directly without any additional formatting.

      Question:
      {question}
      
      Candidate Answers:
      {candidate_answers}

      Count the frequency of each answer and select the most popular one. Output only the chosen answer:

config_name: "benchmark_validation"
datasets: [aime_2025]

models:
  - name: gpt-oss-20b-reason:low
    hf_repo: openai/gpt-oss-20b
    engine: vllm
    model_family: gpt
    card: { params_B: 21.5, layers: 24, hidden_dim: 2880, heads: 64, arch: "decoder-only moe", release_date: "2025-08-05" }
    think_budgets: [80000]
    backend: { dtype: bfloat16, gpu_memory_utilization: 0.95, enforce_eager: true }
    generation: 
      generation_mode: "chat"
      system_prompt: null
      chat_template_kwargs:
        reasoning_effort: "low"
      temperature: 1.0
      top_p: 1.0
      top_k: 0
    reasoning: { style: single_pass, self_consistency_k: 0, self_eval: true, openai_eval: true }
    notes: "Use tokenizer.apply_chat_template (Harmony) or openai-harmony; 131k max_position; sliding_window=128; prev think_budget: 131072."

asd:
  # --- Qwen3 4B ---
  - name: Qwen3-4B-Thinking-2507
    hf_repo: Qwen/Qwen3-4B-Thinking-2507
    engine: vllm
    model_family: qwen
    card: { params_B: 4.0, layers: 36, hidden_dim: 2560, heads: 32, arch: decoder-only (GQA 32Q×8KV) }
    think_budgets: [20000]
    backend: { dtype: bfloat16, gpu_memory_utilization: 0.95, enforce_eager: true }
    generation: { temperature: 0.6, top_p: 0.95, top_k: 20, do_sample: true, max_new_tokens: 512 }
    reasoning: { style: cot, self_consistency_k: 0, self_eval: true, openai_eval: true }
    notes: "262k context; thinking mode." # :contentReference[oaicite:4]{index=4}

  - name: gemma-3-4b-it
    hf_repo: google/gemma-3-4b-it
    engine: vllm
    model_family: gemma
    card: { params_B: 4, layers: 32, hidden_dim: 2048, heads: 16, arch: gemma3_text (decoder-only) }
    think_budgets: [8192]
    backend: { dtype: bfloat16, gpu_memory_utilization: 0.95, enforce_eager: true }
    generation: { temperature: 0.6, top_p: 0.95, do_sample: true, max_new_tokens: 512 }
    reasoning: { style: cot, self_consistency_k: 0, self_eval: true, openai_eval: true }
    notes: "128k input context (Gemma 3 family)." # :contentReference[oaicite:15]{index=15}
