config_name: "bench_fixed_flops"

prompts:
  cot_think: |
    Solve the problem. Show your reasoning ONLY inside <scratchpad>...</scratchpad>.
    <question>
    {question}
    </question>
    <scratchpad>
  plan_think: |
    Devise a short plan ONLY inside <plan>...</plan>.
    <question>
    {question}
    </question>
    <plan>
  answer: |
    Using the information below, output ONLY the final answer inside <final>...</final>.
    <question>
    {question}
    </question>
    {deliberate}
    <final>
  self_eval: |
    You are a strict judge. Reply ONLY YES if the candidate answer equals the gold answer, else NO.
    <question>{question}</question>
    <gold>{gold}</gold>
    <candidate>{candidate}</candidate>
    Judgement:
  direct: |
    Answer the question. Output ONLY inside <final>...</final>.
    <question>{question}</question>
    <final>

datasets: [mmlu, gsm8k, csqa]

models:
  - name: Llama2-7b-chat
    hf_repo: meta-llama/Llama-2-7b-chat-hf
    batch_size: 128
    card: { params_B: 7, layers: 32, hidden_dim: 4096, heads: 32, arch: decoder-only }
    think_budgets: [0]  # ignored by fixed-FLOPs CLI; kept for compatibility
    backend: { dtype: bfloat16, gpu_memory_utilization: 0.45, enforce_eager: true }
    generation: { temperature: 0.1, top_p: 0.9, max_new_tokens: 512 }
    reasoning: { style: cot, self_consistency_k: 0, self_eval: false }

  - name: Llama2-13b-chat
    hf_repo: meta-llama/Llama-2-13b-chat-hf
    batch_size: 64
    card: { params_B: 13, layers: 40, hidden_dim: 5120, heads: 40, arch: decoder-only }
    think_budgets: [0]
    backend: { dtype: bfloat16, gpu_memory_utilization: 0.55, enforce_eager: true }
    generation: { temperature: 0.1, top_p: 0.9, max_new_tokens: 512 }
    reasoning: { style: cot, self_consistency_k: 0, self_eval: false }

  - name: Llama3-8b-instruct
    hf_repo: meta-llama/Meta-Llama-3-8B-Instruct
    batch_size: 96
    card: { params_B: 8, layers: 32, hidden_dim: 4096, heads: 32, arch: decoder-only }
    think_budgets: [0]
    backend: { dtype: bfloat16, gpu_memory_utilization: 0.5, enforce_eager: true }
    generation: { temperature: 0.2, top_p: 0.9, max_new_tokens: 512 }
    reasoning: { style: cot, self_consistency_k: 0, self_eval: false }


